steps:
# Build and push React app
- id: build-react
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ui-app:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  dir: 'ui'
  
- id: push-react  
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ui-app:$COMMIT_SHA']
  
# Build and push FastAPI app  
- id: build-api
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-app:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  dir: 'api'

- id: push-api
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api-app:$COMMIT_SHA']

# Deploy to Cloud Run
- id: deploy-react
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'csv-transformer'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ui-app:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--cpu'
  - '1'
  - '--memory'
  - '1Gi'
  - '--port'
  - '80'
  - '--allow-unauthenticated'
  
- id: deploy-api
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'csv-transformer-api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/api-app:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--port'
  - '80'
  - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY